import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ProvidersLayout from "@/components/layouts/Providers";
import { MainLayout } from "@/components/layouts/MainLayout";


const vazirMatn = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${vazirMatn.variable}  antialiased`}>
        <ProvidersLayout>
          <MainLayout>{children}</MainLayout>
        </ProvidersLayout>
      </body>
    </html>
  );
}
